version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ../static_certificados:/app/static/certificados
      - ../static_uploads:/app/static/uploads
    environment:
      - FLASK_ENV=production
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - BASE_URL=https://docenciamedica.org/
      - MONGO_URI=mongodb://db:27017/
      - TZ=America/Panama
    depends_on:
      - db

  db:
    image: mongo:6.0
    volumes:
      - ../db_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - TZ=America/Panama