version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - static_certificados:/app/static/certificados
      - static_uploads:/app/static/uploads
    environment:
      - MONGO_URI=mongodb://db:27017/
      - TZ=America/Panama
    depends_on:
      - db

  db:
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - TZ=America/Panama

volumes:
  static_certificados:
  static_uploads:
  mongo_data: