version: '3'
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    volumes:
      - ./static/certificados:/app/static/certificados
      - ./static/uploads:/app/static/uploads

  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
