services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ../static_certificados:/app/static/certificados
      - ../static_uploads:/app/static/uploads
      - ../static_usuarios:/app/static/usuarios
      - ../logs:/app/logs
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - MONGO_URI=mongodb://db:27017/
      - TZ=America/Panama
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  db:
    image: mongo:6.0
    volumes:
      - ../db_data:/data/db
    environment:
      - TZ=America/Panama
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s