version: '3.8'

services:
  # Servicio para la aplicación Flask
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - static_certificados:/app/static/certificados
      - static_uploads:/app/static/uploads
    environment:
      - MONGO_URI=mongodb://db:27017/  # Usar "db" como hostname
    depends_on:
      - db

  # Servicio para MongoDB
  db:
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

# Definir volúmenes para persistencia
volumes:
  static_certificados:
  static_uploads:
  mongo_data: